fn Main(args: String) -> int
{
    var x: int = 42;
    var y: int = 10;
    var z: float = 3.14;
    var name: String = "TinyLang";
    var flag1: bool = true;
    // this is a single comment that should be ignored // "dsdhak"
    if (x > y && flag)
    {
        Print(name);
        Print("x is greater than y");
    }
    else
    {
        // Print("x is \"not greater than y");
        Print("hello\"world");
    }

    while (x > 0)
    {
        x = x - 1;
    }

    var errorString: String = "dsadsa"
    return 0;
}